.gitignore
Professor, this is the PR to add `.DS_Store` to `.gitignore`
=> ignore MacOS binary files

JavaParser.astub, build.gradle, src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/UnsolvedClass.java, src/main/java/org/checkerframework/specimin/UnsolvedMethod.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/SameClassName.java, src/test/resources/sameclassname/expected/com/example/Simple.java, src/test/resources/sameclassname/expected/org/second/Calculator.java, src/test/resources/sameclassname/input/com/example/Simple.java, src/test/resources/sameclassname/input/org/first/Calculator.java, src/test/resources/sameclassname/input/org/second/Calculator.java, tempDirJDK/com/example/Simple.java, tempDirJDK/com/github/javaparser/ast/body/GetTypeReturnType.java, tempDirJDK/com/github/javaparser/ast/body/MethodDeclaration.java
Professor, this is the PR to add signature checker to Specimin. Please take a look. Thank you
=> Add signature checker

src/test/java/org/checkerframework/specimin/CallJDK.java, src/test/java/org/checkerframework/specimin/CallJavaParser.java, src/test/java/org/checkerframework/specimin/CrossClassVariable.java, src/test/java/org/checkerframework/specimin/GlobalVariables.java, src/test/java/org/checkerframework/specimin/HiddenTypeTest.java, src/test/java/org/checkerframework/specimin/NoDependenciesReturnsSameTest.java, src/test/java/org/checkerframework/specimin/OneFileSimpleTest.java, src/test/java/org/checkerframework/specimin/SameClassName.java, src/test/java/org/checkerframework/specimin/SpeciminTestExecutor.java, src/test/java/org/checkerframework/specimin/SuperClass.java, src/test/java/org/checkerframework/specimin/ThreeLayerFunction.java, src/test/java/org/checkerframework/specimin/TwoFileSimpleTest.java, src/test/java/org/checkerframework/specimin/UnusedSecondClassTest.java
Professor, for some reasons, I have deleted all of our test files in the past PR. This is the PR to re-add the test files.
=> Re add testfiles

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/UsedMethodsInInnerClass.java, src/test/resources/UsedMethodsInInnerClass/expected/com/example/Baz.java, src/test/resources/UsedMethodsInInnerClass/expected/com/example/Foo.java, src/test/resources/UsedMethodsInInnerClass/input/com/example/Baz.java, src/test/resources/UsedMethodsInInnerClass/input/com/example/Foo.java
Professor,
This is the updated codes so that Specimin can preserve inner classes that contain used methods, and remove classes that don't.
=> Handle used methods in inner classes

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/SuperMethodWithUnsolvedParameters.java, src/test/resources/supermethodwithunsolvedparameters/expected/com/example/Simple.java, src/test/resources/supermethodwithunsolvedparameters/expected/org/example/Unsolved.java, src/test/resources/supermethodwithunsolvedparameters/expected/org/simple/FooReturnType.java, src/test/resources/supermethodwithunsolvedparameters/expected/org/simple/SuperSimple.java, src/test/resources/supermethodwithunsolvedparameters/input/com/example/Simple.java
Professor,
This is the PR to fix the exception in #75.
=> Add codes to handle methods from superclasses with unsolved parameters.

src/main/java/org/checkerframework/specimin/UnsolvedClass.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/GenericTypeTest.java, src/test/resources/generictype/expected/com/example/Simple.java, src/test/resources/generictype/input/com/example/Simple.java
Professor,
This is a simple PR to ignore expressions of generic types when handling paths.
=> Ignore generic types when handling paths

src/main/java/org/checkerframework/specimin/UnsolvedClass.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/TwoTargetsThatUseSameSimpleNameTest.java, src/test/resources/twotargetsthatusesamesimplename/expected/com/example/Bar.java, src/test/resources/twotargetsthatusesamesimplename/expected/com/example/Foo.java, src/test/resources/twotargetsthatusesamesimplename/expected/net/example/Node.java, src/test/resources/twotargetsthatusesamesimplename/expected/org/example/Node.java, src/test/resources/twotargetsthatusesamesimplename/input/com/example/Bar.java, src/test/resources/twotargetsthatusesamesimplename/input/com/example/Foo.java
=> Implement equals and hashcode for UnsolvedClass, removing another infinitely-looping test case

build.gradle, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/SpeciminTestExecutor.java
Should solve #110 (@jonathan-m-phillips please check once this has been merged)
=> Update versions of various tools and implement fixes based on new ErrorProne warning messages

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/UnsovledSymbolVisitorStaticTest.java
While this does resolve the crash in #94, unfortunately that full test case now infinitely loops. I hope #114 will also fix it.
=> Java names cannot contain spaces

src/main/java/org/checkerframework/specimin/SpeciminRunner.java
The improvement here is pretty minimal - basically in the noise on the tests - but it was easy enough to do, and I confirmed that this cache does get enough hits on the tests to make it plausible that this will be an improvement.
Don't merge until the eval script has run, because I want to see whether this improves performance on larger targets or not before we merge.
=> Add a cache to avoid unnecessary calls to `Files.createDirectories`

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
Professor,
This PR handles the other bug that cause `IlegalArgumentException`. I can't make a test for this because I can't isolate the bug. This PR is an attempt to solve cf-3012. So I think we can add cf-3012 as a test case after solving all of its issues,
=> A better way to get packages' names

src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/SuperClassWithGenericTypeTest.java, src/test/resources/superclasswithgenerictype/expected/com/example/Simple.java, src/test/resources/superclasswithgenerictype/expected/org/testing/Parent.java, src/test/resources/superclasswithgenerictype/input/com/example/Simple.java
Professor,
Sorry for requesting your review on these changes again. I have had some difficulties in dealing with git conflict, which required me to start a new PR. Thank you for your understanding.
=> Replace #146 due to git conflict

src/main/resources/target_status.json
The corresponding issue is fixed by #177 in Specimin and this [PR](https://github.com/tahiat/specimin-evaluation/pull/22) in specimen-evaluation.
=> Update expected result for Issue689

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/target_status.json, src/test/java/org/checkerframework/specimin/MultipleBoundTypeParameterTest.java, src/test/java/org/checkerframework/specimin/TypeVariableMethodScope.java, src/test/resources/multipleboundtypeparameter/expected/com/example/Simple.java, src/test/resources/multipleboundtypeparameter/expected/org/testing/PrintReturnType.java, src/test/resources/multipleboundtypeparameter/expected/org/testing/UnsolvedType.java, src/test/resources/multipleboundtypeparameter/input/com/example/Simple.java, src/test/resources/typevariablemethodscope/expected/com/example/Simple.java, src/test/resources/typevariablemethodscope/expected/org/testing/PrintReturnType.java, src/test/resources/typevariablemethodscope/expected/org/testing/UnsolvedType.java, src/test/resources/typevariablemethodscope/input/com/example/Simple.java
Professor,
This PR deals with type parameters having bounds. Please take a look. Thank you.
=> Handle type parameters with bounds to fix 6030b

src/main/java/org/checkerframework/specimin/JavaLangUtils.java, src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/resources/ThrowableImprecision/expected/org/fortest/UnsolvedType.java, src/test/resources/ThrowableImprecision/expected/org/testing/UnsolvedType.java, src/test/resources/ThrowableType/expected/org/testing/UnsolvedType.java
Precursor to #187, review this first. This is a refactoring that doesn't change any behavior.
=> Generalize exception/throwable handling

src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/resources/unsolvednonstaticfield/expected/org/sampling/Baz.java, src/test/resources/unsolvednonstaticfield/expected/org/sampling/OrgSamplingBazCalSyntheticType.java, src/test/resources/unsolvedstaticqualifiedfield/expected/org/sampling/Baz.java, src/test/resources/unsolvedstaticqualifiedfield/expected/org/sampling/OrgSamplingBazMyFieldSyntheticType.java, src/test/resources/unsolvedstaticsimplefield/expected/org/sampling/Baz.java, src/test/resources/unsolvedstaticsimplefield/expected/org/sampling/OrgSamplingBazMyFieldSyntheticType.java
This is a precursor to #187 (and was necessary to get it working). Review before #187.
=> Make it obvious that fields are synthetic

src/main/java/org/checkerframework/specimin/GetTypesFullNameVisitor.java, src/main/java/org/checkerframework/specimin/InheritancePreserveVisitor.java, src/main/java/org/checkerframework/specimin/SolveMethodOverridingVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/MultiLevelInheritanceTest.java, src/test/resources/multilevelinheritance/expected/com/example/Baz.java, src/test/resources/multilevelinheritance/expected/com/example/BazGrandGrandParent.java, src/test/resources/multilevelinheritance/expected/com/example/BazGrandParent.java, src/test/resources/multilevelinheritance/expected/com/example/BazParent.java, src/test/resources/multilevelinheritance/expected/com/example/Foo.java, src/test/resources/multilevelinheritance/expected/org/testing/UnknownAncestor.java, src/test/resources/multilevelinheritance/input/com/example/Baz.java, src/test/resources/multilevelinheritance/input/com/example/BazGrandGrandParent.java, src/test/resources/multilevelinheritance/input/com/example/BazGrandParent.java, src/test/resources/multilevelinheritance/input/com/example/BazParent.java, src/test/resources/multilevelinheritance/input/com/example/Foo.java
Professor,
This PR handles multi-level inheritance. It eliminates compilation error due to unresolved extensions. 
Apart from that, this PR also does two minor changes:
1) Checking if a class is local before trying to get its fully qualified name.
2) Create a temporary scope for lambda if there isn't any.
=> Solve multi level inheritance

src/main/java/org/checkerframework/specimin/InheritancePreserveVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/resources/min_program_compile_status.json, src/test/java/org/checkerframework/specimin/InnerClassUsageTest.java, src/test/resources/innerclassusage/expected/com/example/Baz.java, src/test/resources/innerclassusage/expected/com/example/Foo.java, src/test/resources/innerclassusage/input/com/example/Baz.java, src/test/resources/innerclassusage/input/com/example/Foo.java
This PR updates the inheritance visitor to take inner class and type parameters into consideration. Please take a look. Thank you.
=> Elaborate inheritance visitor

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/resources/min_program_compile_status.json, src/test/java/org/checkerframework/specimin/ImportRemovalStaticTest.java, src/test/resources/importremovalstatic/expected/com/example/Simple.java, src/test/resources/importremovalstatic/expected/org/example/Preconditions.java, src/test/resources/importremovalstatic/input/com/example/Simple.java, src/test/resources/importremovalstatic/input/org/example/Preconditions.java
I'm hopeful that this is the last thing necessary for cf-6388 to pass.
=> Fix how static imports are preserved

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
Professor,
This PR handles the crashing in Issue689. It's mainly about adding catches for exceptions here and there.
=> Fix crashing 689

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/UnsolvedMethodWithArrayParameter.java, src/test/resources/unsolvedmethodwitharrayparameter/expected/com/example/Simple.java, src/test/resources/unsolvedmethodwitharrayparameter/expected/org/testing/OrgTestingUnsolvedTypeProcessArrayReturnType.java, src/test/resources/unsolvedmethodwitharrayparameter/expected/org/testing/UnsolvedType.java, src/test/resources/unsolvedmethodwitharrayparameter/input/com/example/Simple.java
Professor,
I figured out this issue while trying to fix a crashing project. Please take a look. Thank you.
=> Handle unsolved parameters with array types.

src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/test/java/org/checkerframework/specimin/OverridingReturnTypeMatchingTest.java, src/test/resources/overridingreturntypematching/expected/com/example/Simple.java, src/test/resources/overridingreturntypematching/expected/org/testing/SimpleParent.java, src/test/resources/overridingreturntypematching/input/com/example/Simple.java
Professor,
This PR handles the mismatching in return types that we discussed yesterday. Please take a look. Thank you.
=> Handle return types mismatching

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/resources/min_program_compile_status.json, src/test/resources/lambdaquadfunction/expected/org/example/SyntheticFunction4.java, src/test/resources/lambdatriconsumer/expected/org/example/SyntheticConsumer3.java, src/test/resources/lambdatrifunction/expected/org/example/SyntheticFunction3.java, src/test/resources/lambdatrifunction2/expected/org/example/SyntheticFunction3.java
Professor,
This is a simple PR to remove all FunctionalInterface annotations. Please take a look. Thank you.
=> Remove FunctionalInterface anotations

src/main/java/org/checkerframework/specimin/UnsolvedMethod.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/UnsolvedOverrideAnnotationTest.java, src/test/resources/unsolvedoverrideannotation/expected/com/example/Foo.java, src/test/resources/unsolvedoverrideannotation/expected/org/testing/Baz.java, src/test/resources/unsolvedoverrideannotation/input/com/example/Foo.java
Professor,
This PR handles the missing overridden method bug related to cf-577. Please take a look. Thank you.
=> Handle Override annotation

src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java
Produces a nice table. I'm using this while debugging preservation status problems, and figured it should go into main.
=> Helpful error message when target method is not found

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/AnnoInGenericTargetTest.java, src/test/resources/annoingenerictarget/expected/com/example/Simple.java, src/test/resources/annoingenerictarget/input/com/example/Simple.java
This was preventing me from testing a hypothesis related to cf-691. Sadly, my hypothesis was wrong (but this code allowed me to prove it!), so I'm still working on that.
=> Fix bug in TargetMethodFinderVisitor's handling of annotations

src/main/java/org/checkerframework/specimin/InheritancePreserveVisitor.java, src/test/java/org/checkerframework/specimin/InterfaceReappearanceTest.java, src/test/resources/interfacereappearance/expected/com/example/Baz.java, src/test/resources/interfacereappearance/expected/com/example/Foo.java, src/test/resources/interfacereappearance/input/com/example/Baz.java, src/test/resources/interfacereappearance/input/com/example/Foo.java
Professor,
This PR fixes the infinite loop problem mentioned in #234. Please take a look. Thank you.
=> Avoid infinite loop in InheritancePreserveVisitor

src/main/java/org/checkerframework/specimin/PrunerVisitor.java
Professor,
This PR fixes a small bug found in #234. Please take a look. Thank you.
=> Static and Default can't be together

src/main/java/org/checkerframework/specimin/EnumVisitor.java, src/main/java/org/checkerframework/specimin/FieldDeclarationsVisitor.java, src/main/java/org/checkerframework/specimin/GetTypesFullNameVisitor.java, src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedMethod.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
#89 has gotten out of date, but many of the refactorings that @jonathan-m-phillips proposed are still relevant. This PR supersedes #89 and adds these refactorings to the current code base.
co-authored by @jonathan-m-phillips
=> Refactorings based on #89

src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedMethod.java, src/test/java/org/checkerframework/specimin/OverrideDoubleTest.java, src/test/resources/overridedouble/expected/com/example/Simple.java, src/test/resources/overridedouble/expected/org/example/Frame.java, src/test/resources/overridedouble/expected/org/example/InstConstraintVisitor.java, src/test/resources/overridedouble/input/com/example/Simple.java
=> Don't add the same method twice to an unsolved class

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/ForEachLocalTest.java, src/test/resources/foreachlocal/expected/com/example/Bar.java, src/test/resources/foreachlocal/expected/com/example/DoSomethingReturnType.java, src/test/resources/foreachlocal/expected/com/example/Foo.java, src/test/resources/foreachlocal/expected/com/example/Simple.java, src/test/resources/foreachlocal/input/com/example/Simple.java
Fixes #165 
Also did a minor optimization and a minor change to error reporting (for debugging purposes).
=> Add the loop variable of a for each loop to the local variable map

src/main/java/org/checkerframework/specimin/JavaLangUtils.java, src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/test/java/org/checkerframework/specimin/BooleanExprTest.java, src/test/resources/booleanexpr/expected/com/example/Foo.java, src/test/resources/booleanexpr/expected/com/example/Simple.java, src/test/resources/booleanexpr/input/com/example/Simple.java
TODO: also look into unary expressions ~~and the `==` and `!=` operators~~ later.
~~TODO: tests for other operators?~~
=> Fix handling of boolean expressions

.github/workflows/gradle.yml, build.gradle, src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/TwoTypeCorrect2Test.java, src/test/java/org/checkerframework/specimin/TwoTypeCorrectTest.java, src/test/resources/foreachlocal/expected/com/example/Bar.java, src/test/resources/foreachlocal/expected/com/example/Foo.java, src/test/resources/twotypecorrect/expected/com/example/Simple.java, src/test/resources/twotypecorrect/expected/org/example/ClassOrInterfaceType.java, src/test/resources/twotypecorrect/expected/org/example/PrimitiveType.java, src/test/resources/twotypecorrect/expected/org/example/Type.java, src/test/resources/twotypecorrect/input/com/example/Simple.java, src/test/resources/twotypecorrect2/expected/com/example/Simple.java, src/test/resources/twotypecorrect2/expected/org/example/ClassOrInterfaceType.java, src/test/resources/twotypecorrect2/expected/org/example/PrimitiveType.java, src/test/resources/twotypecorrect2/expected/org/example/Type.java, src/test/resources/twotypecorrect2/input/com/example/Simple.java
=> Use instanceof expressions to avoid infinite loop in Randoop

src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/test/java/org/checkerframework/specimin/ForEachIterableTest.java, src/test/resources/foreachiterable/expected/com/example/Simple.java, src/test/resources/foreachiterable/expected/org/example/Baz.java, src/test/resources/foreachiterable/expected/org/example/Foo.java, src/test/resources/foreachiterable/input/com/example/Simple.java
=> Make types that appear as the iterable in a for-each loop become arrays

src/main/java/org/checkerframework/specimin/InheritancePreserveVisitor.java, src/main/java/org/checkerframework/specimin/JavaLangUtils.java, src/main/java/org/checkerframework/specimin/JdkTypeSolver.java, src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/JdkCompilerTest.java, src/test/resources/jdkcompiler/expected/com/example/Simple.java, src/test/resources/jdkcompiler/input/com/example/Simple.java
=> Handle JDK internals in target files

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
I don't have a test case for this problem, since I noticed it while investigating another, unrelated issue (#298).
I think it should be clear what the issue is and that this fix is correct, though.
=> Fix package name computation

.github/dependabot.yml
See documentation here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> Add dependabot for package updates

DEVELOPERS.md, README.md
@theron-wang please take a look at this as you're trying to debug the failures you're seeing on #302. If there's anything you think we should add, I'd appreciate your feedback.
=> Developer docs

src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/SolveMethodOverridingVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/SpeciminStateVisitor.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java
This doesn't need a review from both @LoiNguyenCS and @theron-wang, just from one of you (whoever gets to it first is fine).
I also removed some fields from the visitors that weren't ever used.
=> Refactor visitors to share state and simplify constructing one visitor from the previous one
