README.md, build.gradle
Professor, when I try to run `Specimin` on my computer, I got some errors from `gradle`, such as `Unknown command-line option '--outputDirectory'.`. I have made some small changes to the `build.gradle` and the instruction to run `Specimin` in the `README.md`. Those changes have helped my local version of `Specimin` run properly. Please take a look.
=> Run with gradle

.github/workflows/gradle.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties
This should let us build Specimin with a modern JDK, and also hopefully fix the issue @LoiNguyenCS is seeing with Spotless, by updating it to the latest version
=> Update dependency versions

src/main/java/org/checkerframework/specimin/SpeciminRunner.java
Professor, this is the PR to separate the main method of SpeciminRunner as we've discussed. Please let me know if there is anything I need to change.
=> separate minimization part

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/MethodCalledByFieldTest.java, src/test/resources/methodcalledbyfield/expected/com/example/Simple.java, src/test/resources/methodcalledbyfield/expected/org/math/Calculator.java, src/test/resources/methodcalledbyfield/input/com/example/Simple.java
This PR should fix the remaining problems with #41. Two changes that this PR makes are:
1. Add codes to update used elements (classes and methods) for method calls that are called by fields in `TargetMethodFinderVisitor`.
2. Have a more precise way to update `gotException` in `UnsolvedSymbolVisitor`.
=> update codes to fix ashe

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/PrimitiveArrayTest.java, src/test/resources/primitivearray/expected/com/example/Simple.java, src/test/resources/primitivearray/input/com/example/Simple.java
Professor,
This is a simple PR for Specimin to handle fields with primitive array types. For some reasons, JavaParser will throw an exception if we try to resolve fields with primitive array types, but it does not have any problems resolving methods with that same type.
=> add codes and tests for primitive array

src/main/java/org/checkerframework/specimin/UnsolvedClass.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
This simplifies the API and gives me confidence that `getClassName` really is the simple class name.
I made these changes as part of my investigation into #87, but this PR does **not** fix #87.
=> Refactor how type variables are handled by UnsolvedClass

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
I confirmed on the full test case for #87 that this fixes the reported problem with missing classes like this one that have a type variable signature in the type of a field:
```
package org.checkerframework.dataflow.analysis;
public class OrgCheckerframeworkDataflowAnalysisAbstractAnalysis<V, S, T>CurrentTreeType {
}
```
This PR removes the "<V, S, T>" from this field's type. Unfortunately, this still doesn't fix #87.
=> Don't print type variable signature in name of fields

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/GenericTypeMethodTest.java, src/test/resources/generictypemethod/expected/com/example/Baz.java, src/test/resources/generictypemethod/expected/com/example/Foo.java, src/test/resources/generictypemethod/expected/org/testing/UnsolvedType.java, src/test/resources/generictypemethod/input/com/example/Baz.java, src/test/resources/generictypemethod/input/com/example/Foo.java
Professor,
This is the PR to enforce that original class files are kept untouched.
Given an original class in the input codebase with generic types, such as `Resolved<T, V>`, if that type is used with unsolved type parameters, such as `Resolved<Unsolved, Unsolved>`, Specimin can confuse `Resolved` to be an unsolved type that needs synthetic classes created. It is rather difficult to solve this confusion of Specimin, since JavaParser does not have any straightforward mechanism to separate a type from its type parameters. It's easier to prevent Specimin to make any changes to original class files. And when the unsolved type parameters are solved by the visit method for `ClassOrInterfaceType`, the problem will disappear automatically.
=> Codes to keep original class files

src/main/java/org/checkerframework/specimin/SpeciminRunner.java
This PR addresses a minor enhancement by automatically appending an ending slash to the root directory if one is not present.
=> Make sure root ends with slash

build.gradle
Speeds up `./gradlew test` from ~50 seconds to ~15 seconds on my laptop. (Still too slow, but much better!)
=> Speed up tests by running them in parallel

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/BooleanReturnTest.java, src/test/resources/booleanreturn/expected/com/example/Simple.java, src/test/resources/booleanreturn/expected/org/example/ElementUtils.java, src/test/resources/booleanreturn/expected/org/example/Foo.java, src/test/resources/booleanreturn/input/com/example/Simple.java
In particular, Specimin does not create the `org.example.Foo#isGood()` method (I'm not sure why).
The goal of this test was to make sure that Specimin correctly makes methods/fields that need to return booleans (because they are used in if guards) actually have boolean returns (instead of a synthetic return class). That part seems to be working (good!), but I'm not sure why the `isGood()` method isn't created. @LoiNguyenCS can you take a look at this and either 1) fix it, or 2) let me know why my test case isn't correct? Thanks.
=> Failing test case where a used method is not created properly by Specimin

build.gradle, src/test/java/org/checkerframework/specimin/ExtendsSourceButNotTargetTest.java, src/test/resources/extendssourcebutnottarget/expected/com/example/B.java, src/test/resources/extendssourcebutnottarget/expected/com/example/C.java, src/test/resources/extendssourcebutnottarget/expected/com/example/Simple.java, src/test/resources/extendssourcebutnottarget/input/com/example/B.java, src/test/resources/extendssourcebutnottarget/input/com/example/C.java, src/test/resources/extendssourcebutnottarget/input/com/example/Simple.java
@LoiNguyenCS this test is based on our conversation yesterday, where you hypothesized that a test case like this one would trigger an infinite loop. It doesn't do that, but the output is not compilable: no `B.java` is produced, but `Simple` still extends `B`.
=> Another failing test case

.github/workflows/gradle.yml, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
Professor,
This is the PR to make Specimin solves as less symbols as possible. The best thing about this is that the less symbols `UnsolvedSymbolVisitor` try to solve, the less chance Specimin will crash :-) Hopefully this PR makes the evaluation script runs too.
=> Try to solve less symbols

src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java
I've noticed that the tests produce `.class` files locally sometimes, which is definitely undesirable behavior.
I would have preferred to disable code generation rather than just putting the `.class` files somewhere else (since either way code generation is definitely creating I/O we don't need!), but this at least hides the problem from users.
=> Avoid generating .class files

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/test/resources/MethodInEnum/expected/com/example/Foo.java, src/test/resources/implicitinterfaceaccessmethodoverload/expected/com/example/Simple.java
Professor,
Turns out that the field `isInsideAnInterface` was buggy; once set to `true`, it remained permanently in that state. So I have removed that field. I have also fixed a test file we had in the past, where a used method should have an empty body.
=> remove isInsideInterface

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/MultipleVariableDeclaratorsTest.java, src/test/resources/multiplevariabledeclarators/expected/com/example/Simple.java, src/test/resources/multiplevariabledeclarators/input/com/example/Simple.java
Note that for debugging purposes, this PR already includes the change in #131. Merge #131 before reviewing this PR.
@LoiNguyenCS is there a better way to get the full class name in `PrunerVisitor` that you're aware of? I'm not particularly confident in how I did it, but it seems to work on the test cases.
The change in `TargetMethodFinderVisitor` is necessary because without it, code like:
```
baz(obj1);
```
where `obj1` is a field fail to register `obj1` as a used member. Removing that logic didn't cause a test to fail, so I'm not sure why it was there. @LoiNguyenCS do you know why it was originally present? There's no documentation that I can see, and `git blame` doesn't help (it points to https://github.com/kelloggm/specimin/commit/fac443546259ad285f446a2ae39377ac3d26b4d5, which …
=> Handle fields with multiple variable declarators

src/main/java/org/checkerframework/specimin/FieldDeclarationsVisitor.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/test/java/org/checkerframework/specimin/FieldInEnumTest.java, src/test/java/org/checkerframework/specimin/UnrelatedEnumTest.java, src/test/resources/fieldinenum/expected/com/example/Foo.java, src/test/resources/fieldinenum/input/com/example/Foo.java, src/test/resources/unrelatedenum/expected/com/example/Simple.java, src/test/resources/unrelatedenum/input/com/example/Foo.java, src/test/resources/unrelatedenum/input/com/example/Simple.java, typecheck_test_outputs.sh
Fixes a crash in CF-6388, although I haven't yet checked if that target has other problems. The proximate cause of the crash was `FieldDeclarationsVisitor`, with the following stack trace:
```
Exception in thread "main" java.lang.ClassCastException: class com.github.javaparser.ast.body.EnumDeclaration cannot be cast to class com.github.javaparser.ast.body.ClassOrInterfaceDeclaration (com.github.javaparser.ast.body.EnumDeclaration and com.github.javaparser.ast.body.ClassOrInterfaceDeclaration are in unnamed module of loader 'app')
at org.checkerframework.specimin.FieldDeclarationsVisitor.visit(FieldDeclarationsVisitor.java:38)
at org.checkerframework.specimin.FieldDeclarationsVisitor.visit(FieldDeclarationsVisitor.java:20)
at com.github.javaparser.ast.body.FieldDeclaration.accept(FieldDecla …
```
=> Resolve crash when encountering a field inside an enum

build.gradle
Dependent lib class are not included in the specimin jar file currently. Which causes ClassNotFound exception when running the project from jar.
=> adding dependency in target jar file

src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/ThrowableImprecisionTest.java, src/test/java/org/checkerframework/specimin/ThrowableTypeTest.java, src/test/resources/ThrowableImprecision/expected/com/example/Baz.java, src/test/resources/ThrowableImprecision/expected/com/example/Foo.java, src/test/resources/ThrowableImprecision/expected/org/fortest/OrgFortestUnsolvedTypeGetTypeReturnType.java, src/test/resources/ThrowableImprecision/expected/org/fortest/UnsolvedType.java, src/test/resources/ThrowableImprecision/expected/org/testing/UnsolvedType.java, src/test/resources/ThrowableImprecision/input/com/example/Baz.java, src/test/resources/ThrowableImprecision/input/com/example/Foo.java, src/test/resources/ThrowableType/expected/com/example/Simple.java, src/test/resources/ThrowableType/expected/org/testing/UnsolvedType.java, src/test/resources/ThrowableType/input/com/example/Simple.java
Professor,
This PR addresses the issue that some synthetic types need to extend `Throwable` in order for the output to compile.
=> Handle synthetic types that extend Throwable

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
This is the second time I've had to write this logic, so I figured we should include it in UnsolvedSymbolVisitor directly. It shouldn't have a perf impact as long as `DEBUG` is false, but it makes it easy to switch it on when it's needed (when debugging an infinite loop caused by `gotException` being set to true even though nothing is changing).
=> Debug logic for infinite loops

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/target_status.json, src/test/java/org/checkerframework/specimin/WildcardImport2Test.java, src/test/java/org/checkerframework/specimin/WildcardImport3Test.java, src/test/java/org/checkerframework/specimin/WildcardImport4Test.java, src/test/java/org/checkerframework/specimin/WildcardImportTest.java, src/test/resources/wildcardimport/expected/com/example/Simple.java, src/test/resources/wildcardimport/expected/org/example/Foo.java, src/test/resources/wildcardimport/expected/org/example/FooMethodReturnType.java, src/test/resources/wildcardimport/input/com/example/Simple.java, src/test/resources/wildcardimport2/expected/com/example/Simple.java, src/test/resources/wildcardimport2/expected/org/example/Foo.java, src/test/resources/wildcardimport2/expected/org/example/FooMethodReturnType.java, src/test/resources/wildcardimport2/input/com/example/Simple.java, src/test/resources/wildcardimport3/expected/com/example/Simple.java, src/test/resources/wildcardimport3/expected/org/anotherexample/Foo.java, src/test/resources/wildcardimport3/input/com/example/Simple.java, src/test/resources/wildcardimport3/input/org/anotherexample/Foo.java, src/test/resources/wildcardimport4/expected/com/example/Foo.java, src/test/resources/wildcardimport4/expected/com/example/Simple.java, src/test/resources/wildcardimport4/input/com/example/Foo.java, src/test/resources/wildcardimport4/input/com/example/Simple.java
It is likely that this feature is under-tested, so I strongly suggest trying to come up with ways to break it :)
=> Allow Specimin to handle wildcard imports even in non-jar mode

README.md
Professor,
This PR updates the README so that users don't add receiver parameters to signatures of target methods. Please take a look. Thank you.
Note: the CI is failing because we need to update the result of cf-3020.
=> Update README to ignore receiver parameters

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/target_status.json, src/test/java/org/checkerframework/specimin/TypeVarParameterTest.java, src/test/resources/typevarparameter/expected/com/example/Simple.java, src/test/resources/typevarparameter/input/com/example/Simple.java
Professor,
This PR fixes cf-3021 issue. It adds a simple check for type variables before trying to resolve types. Please take a look. Thank you.
=> Check for type var before resolving in declaredInCurrentClass

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/target_status.json, src/test/java/org/checkerframework/specimin/ParameterWithAnnotationsTest.java, src/test/resources/parameterwithannotations/expected/com/example/Simple.java, src/test/resources/parameterwithannotations/expected/org/testing/UnsolvedType.java, src/test/resources/parameterwithannotations/input/com/example/Simple.java, src/test/resources/parameterwithannotations/input/org/testing/UnsolvedType.java
This PR ignores annotations in target method signatures. Due to the difficulty in keeping space consistency after removing annotations, such as the transformation of `byte @Nullable []` to `byte[]` (removing both starting and ending spaces), versus `int x, @Nullable int b`, which becomes `int x, int b` (only removing the ending space), this PR removes all spaces from target method signatures prior to comparison.
=> Ignore annotations in target method signatures

src/main/java/org/checkerframework/specimin/UnsolvedAnnotationRemoverVisitor.java, tempDir3/java/util/Simple.java
Professor,
This PR uses isJavaLangName instead of having a set of predefined java.lang annotations. It requires an approval to be merged. Please take a look. Thank you.
=> Use isJavaLangName instead

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/EnumConstantArgTest.java, src/test/resources/enumconstantarg/expected/com/example/Foo.java, src/test/resources/enumconstantarg/expected/org/example/Op.java, src/test/resources/enumconstantarg/input/com/example/Foo.java
This fixes one of the compilation bugs in CF-6077 (i.e., the integration test target derived from Apache Cassandra); there are others (including, I think, the one that #191 is intended to solve). This PR only handles enum constants; I don't expect CF-6077 to compile with just this PR.
We already are very approximate with enum constants (see #81 for example), so this change just acknowledges that. The implementation is a bit hacky, but it's cleaner than trying to add another boolean that we'd need to check in each other visit method.
=> Preserve arguments to enum constructors called in enum constants

src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/SolveMethodOverridingVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/UnsolvedAnnotationRemoverVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/AbstractImplTest.java, src/test/java/org/checkerframework/specimin/AbstractOverride2Test.java, src/test/java/org/checkerframework/specimin/AbstractOverrideTest.java, src/test/resources/abstractimpl/expected/com/example/Simple.java, src/test/resources/abstractimpl/expected/com/example/WrappedSet.java, src/test/resources/abstractimpl/input/com/example/Simple.java, src/test/resources/abstractimpl/input/com/example/WrappedSet.java, src/test/resources/abstractoverride/expected/com/example/AbstractSimple.java, src/test/resources/abstractoverride/expected/com/example/Simple.java, src/test/resources/abstractoverride/input/com/example/AbstractSimple.java, src/test/resources/abstractoverride/input/com/example/Simple.java, src/test/resources/abstractoverride2/expected/com/example/Simple.java, src/test/resources/abstractoverride2/input/com/example/AbstractSimple.java, src/test/resources/abstractoverride2/input/com/example/Simple.java, src/test/resources/anonymousclass/expected/com/example/Simple.java, src/test/resources/innerclasscomplex/expected/com/example/AbstractAnalysis.java, src/test/resources/interfaceimplemented/expected/com/example/Foo.java, src/test/resources/interfacemethodwithunsolvedtype/expected/com/example/Foo.java, src/test/resources/interfacewithgenerictype/expected/com/example/Foo.java, src/test/resources/interfacewithunsolvedsymbols/expected/com/example/Foo.java, src/test/resources/superclass/expected/com/example/Simple.java
This prevents warnings like this one, in the integration test cf-3022, when compiling Specimin's output:
```
./com/google/common/collect/AbstractMapBasedMultimap.java:114: error: AbstractMapBasedMultimap.WrappedCollection is not abstract and does not override abstract method size() in AbstractCollection
class WrappedCollection extends AbstractCollection<V> {
^
```
The key problem is making sure that we preserve methods that are necessary because an abstract class/interface doesn't actually define an implementation for them.
=> Preserve overrides that are required for compilability

src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/resources/min_program_compile_status.json
Professor,
This PR updates the `MustImplementMethodsVisitor` to consider all overriding methods as should be preserved if they are overriding abstract methods from the built-in packages of Java. 
=> Consider all abstracts for built-in packages of the Java language.

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/test/resources/wildcardimport/expected/com/example/Simple.java, src/test/resources/wildcardimport2/expected/com/example/Simple.java, src/test/resources/wildcardimport3/expected/com/example/Simple.java
This PR fixes some compilation errors in `cf-6030`. The problem occurs because not all classes have access to every class in the list of used classes. So, it's risky to transform a wildcard import based on that list. Unfortunately, I couldn't find a good way to write a test case to show this bug.
=> Preserve wildcard imports

src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedMethod.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/TypeVarMatchingTest.java, src/test/resources/typevarmatching/expected/com/example/Simple.java, src/test/resources/typevarmatching/expected/org/testing/SimpleParent.java, src/test/resources/typevarmatching/input/com/example/Simple.java
Professor,
This PR introduces a new field in `UnsolvedClassOrInterfaceType` to make sure that we don't have compilation error due to mismatches in type variables. 
In the provided test case, if we have `SimpleParent<T, T1>`, there arises a potential issue when the javac updates the synthetic type of `get()` to `V`. This update would result in a type variable mismatch within the `SimpleParent` class.
=> Type var consistency

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/min_program_compile_status.json, src/test/java/org/checkerframework/specimin/NullArgTest.java, src/test/resources/nullarg/expected/com/example/Simple.java, src/test/resources/nullarg/expected/org/example/Baz.java, src/test/resources/nullarg/expected/org/example/QuxReturnType.java, src/test/resources/nullarg/input/com/example/Simple.java
This PR also includes a significant refactoring to unite the code that's used for inferring parameter types from arguments. Previously, we had three copies of it (only one of which has been modified by @LoiNguyenCS's recent PRs) - one for method call expressions, another for object creation expressions, and a third for explicit constructor invocations. Now all these locations call into the same routine (derived from the method call code), so fixes in one location will apply to all three.
=> Correctly preserve methods with a null argument

src/main/java/org/checkerframework/specimin/JavaLangUtils.java, src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/min_program_compile_status.json, src/test/java/org/checkerframework/specimin/LambdaBodyStaticUnsolved2Test.java, src/test/java/org/checkerframework/specimin/LambdaBodyStaticUnsolvedTest.java, src/test/resources/lambdabodystaticunsolved/expected/com/example/Simple.java, src/test/resources/lambdabodystaticunsolved/expected/com/example/nullness/Nullness.java, src/test/resources/lambdabodystaticunsolved/expected/com/example/sql/SqlNode.java, src/test/resources/lambdabodystaticunsolved/expected/com/example/sql/SqlParserPos.java, src/test/resources/lambdabodystaticunsolved/expected/com/example/util/Util.java, src/test/resources/lambdabodystaticunsolved/input/com/example/Simple.java, src/test/resources/lambdabodystaticunsolved/input/com/example/sql/SqlNode.java, src/test/resources/lambdabodystaticunsolved/input/com/example/sql/SqlParserPos.java, src/test/resources/lambdabodystaticunsolved/input/com/example/util/Util.java, src/test/resources/lambdabodystaticunsolved2/expected/com/example/Simple.java, src/test/resources/lambdabodystaticunsolved2/expected/com/example/nullness/Nullness.java, src/test/resources/lambdabodystaticunsolved2/expected/com/example/sql/SqlNode.java, src/test/resources/lambdabodystaticunsolved2/expected/com/example/sql/SqlParserPos.java, src/test/resources/lambdabodystaticunsolved2/expected/com/example/util/Util.java, src/test/resources/lambdabodystaticunsolved2/input/com/example/AnotherClass.java, src/test/resources/lambdabodystaticunsolved2/input/com/example/Simple.java, src/test/resources/lambdabodystaticunsolved2/input/com/example/sql/SqlNode.java, src/test/resources/lambdabodystaticunsolved2/input/com/example/sql/SqlParserPos.java, src/test/resources/lambdabodystaticunsolved2/input/com/example/util/Util.java
This PR contains three related fixes, all of which are necessary to get CF-3850 (and therefore the new test case in this PR) to compile:
* we need to add something to the list of arguments for a synthetic method as a placeholder if `null` is passed. This PR just adds "Object" there.
* the strategy for handling constraints in JavaTypeCorrect has changed to handle constraints with multiple types in them (they're comma-separated). This is necessary to trigger the appropriate type correction so that the return type of `castNonNull` is compatible with the lambda (there are two lower bounds).
* `updateTypeForSyntheticClasses` has been changed to attempt to use a fully-qualified name when possible, because otherwise there is an unsolved symbol once we correctly mark the return type of …
=> Make CF-3850 compilable

src/main/java/org/checkerframework/specimin/PrunerVisitor.java
Professor,
This PR makes sure that Specimin empties out the content of all non-target methods, even the methods inside a functional interface. Please take a look. Thank you.
=> Avoid unsolved symbols in functional interface methods

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
Professor,
This PR fixes one of the crashes in #221.
I can not figure out the specific case where `JavaParser` will fail if there are generic types, hence the word "sometimes" in the explanatory comments. It seems to be that we need to have a generic type with generic bound or something similar for `JavaParser` to fail.
Right now this limitation of `JavaParser` only affect the jar mode, so it is not too serious.  
"
=> Address the limitation of JavaParser

src/main/java/org/checkerframework/specimin/JavaTypeCorrect.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/resources/min_program_compile_status.json, src/test/java/org/checkerframework/specimin/UnsolvableInterfaceTest.java, src/test/resources/unsolvableinterface/expected/com/example/Baz.java, src/test/resources/unsolvableinterface/expected/com/example/Foo.java, src/test/resources/unsolvableinterface/input/com/example/Foo.java, src/test/resources/unsolvableinterfacehardcase/expected/com/example/AddReturnType.java, src/test/resources/unsolvableinterfacehardcase/expected/com/example/Baz.java, src/test/resources/unsolvableinterfacehardcase/expected/com/example/Foo.java, src/test/resources/unsolvableinterfacehardcase/input/com/example/Foo.java, src/test/resources/unsolvableinterfaceprettyhardcase/expected/com/example/Baz.java, src/test/resources/unsolvableinterfaceprettyhardcase/expected/com/example/Foo.java, src/test/resources/unsolvableinterfaceprettyhardcase/input/com/example/Baz.java, src/test/resources/unsolvableinterfaceprettyhardcase/input/com/example/Foo.java
Professor,
This PR removes interfaces that cannot be resolved for successful compilation  These are interfaces from the java packages. This issue only happens if we isolate the input file from its codebase. Please take a look. Thank you.
=> Remove completely unresolvable interfaces

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/InterfaceUseComplexTest.java, src/test/resources/interfaceusecomplex/expected/com/example/Baz.java, src/test/resources/interfaceusecomplex/expected/com/example/Foo.java, src/test/resources/interfaceusecomplex/input/com/example/Foo.java
Previously, the synthetic method for `containsAll` in `Baz` had the parameter type `com.example.Baz` (without the `<?>`, meaning it is a raw type). There are two problems with that:
* raw types trigger a warning from javac by default
* in this case, it causes the output not to compile (because the implicit override is not correct - the types aren't compatible)
Based on an example I found while investigating cf-691.
=> Don't create raw types

src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/NavigableSetExample2.java, src/test/resources/navigablesetexample2/expected/com/example/NavigableSet.java, src/test/resources/navigablesetexample2/expected/com/example/Simple.java, src/test/resources/navigablesetexample2/input/com/example/Simple.java
Unfortunately I had to make `isAnInterface` non-final, but I couldn't figure out a way to check whether there is such an `implements` clause at the point where I wrote the new comment around line 1500 (which is the ideal place to fix this).
I also made one small refactoring to get rid of an antipattern.
=> Unsolved return types could be interfaces

build.gradle, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/test/java/org/checkerframework/specimin/JarFileTest.java, src/test/resources/jarfile/expected/an/old/library/Book.java
Professor,
This is the PR to invoke a decompiler. I have decided to use [VineFlower](https://vineflower.org). It is built based on [FernFlower](https://github.com/fesh0r/fernflower). However, VineFlower supports Gradle, and it seems to be [cooler](https://www.reddit.com/r/java/comments/ue8u59/new_open_source_java_decompiler/) according to its creator. :-)
Sorry for adding the try-catch statements when parsing the file. As explained in the comments, it is actually difficult to fix a bug that can't be reproduced locally. But since those bugs do not happen locally., I think we don't have to worry about them.
=> Use decompiler

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/NavigableSetFieldExample.java, src/test/resources/navigablesetfieldexample/expected/com/example/NavigableSet.java, src/test/resources/navigablesetfieldexample/expected/com/example/Simple.java, src/test/resources/navigablesetfieldexample/input/com/example/Simple.java
This adopts the same strategy we use for "regular" method calls.
Fixes one crash on CF-691. However, another is revealed.
=> Skip processing explicit constructor invocations until all arguments can be solved

src/main/java/org/checkerframework/specimin/InheritancePreserveVisitor.java, src/main/resources/min_program_compile_status.json, src/main/resources/preservation_status.json, src/test/java/org/checkerframework/specimin/SuperinterfaceExtendsTest.java, src/test/resources/abstractoverride2/expected/com/example/AbstractSimple.java, src/test/resources/abstractoverride2/expected/com/example/Simple.java, src/test/resources/implicitinterfaceaccesswithmanyinterfaces/expected/com/example/Simple.java, src/test/resources/implicitinterfaceaccesswithmanyinterfaces/expected/org/testing/B.java, src/test/resources/implicitinterfaceaccesswithmanyinterfaces/expected/org/testing/C.java, src/test/resources/superinterfaceextends/expected/com/example/PropertyFactory.java, src/test/resources/superinterfaceextends/expected/com/example/PropertyFactoryManager.java, src/test/resources/superinterfaceextends/expected/com/example/ReadableProperty.java, src/test/resources/superinterfaceextends/expected/com/example/WritableProperty.java, src/test/resources/superinterfaceextends/input/com/example/PropertyFactory.java, src/test/resources/superinterfaceextends/input/com/example/PropertyFactoryManager.java, src/test/resources/superinterfaceextends/input/com/example/ReadableProperty.java, src/test/resources/superinterfaceextends/input/com/example/WritableProperty.java, src/test/resources/unsolvedinterface/expected/com/example/Foo.java, src/test/resources/unsolvedinterface/expected/org/testing/Baz.java, src/test/resources/unusedinterface/expected/com/example/Baz.java, src/test/resources/unusedinterface/expected/com/example/Foo.java, src/test/resources/unusedtypeparameterbound/expected/com/example/Simple.java, src/test/resources/unusedtypeparameterbound/expected/org/testing/Foo.java, src/test/resources/unusedtypeparameterbound/input/org/testing/Foo.java, typecheck_test_outputs.sh
This should be part of the modularity model. The previous test case that showed we didn't do this was wrong, and I should not have approved it.
Should fix JDK-8319461.
=> Preserve the bounds of the type parameters of used classes

src/test/java/org/checkerframework/specimin/UnaryExprTest.java, src/test/resources/unaryexpr/expected/com/example/Foo.java, src/test/resources/unaryexpr/expected/com/example/Simple.java, src/test/resources/unaryexpr/input/com/example/Simple.java
Based on the bug that was fixed by #262, I was concerned that our handling of unary expressions might also be incorrect. I checked for a test case, and found that we didn't have one (because we didn't have a test containing the string `+=`), so I wrote the one in this PR. To my pleasant surprise, the test passes - I think our usual type correct algorithm actually handles this case just fine, since there is no special error message for mistakes in unary operator types (as there is for binary operators).
=> Test for unary expressions

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/UnsolvedMethodTypeCorrectTest.java, src/test/resources/unsolvedmethodtypecorrect/expected/com/example/Simple.java, src/test/resources/unsolvedmethodtypecorrect/expected/org/example/Foo.java, src/test/resources/unsolvedmethodtypecorrect/expected/org/example/LocalVariables.java, src/test/resources/unsolvedmethodtypecorrect/expected/org/example/SetReturnType.java, src/test/resources/unsolvedmethodtypecorrect/input/com/example/Simple.java
Also incidentally cleaned up some ISSTA tech debt that happened to get in the way.
=> Don't lose information in synthetic types when correcting their type via JavaTypeCorrect

src/main/java/org/checkerframework/specimin/SpeciminRunner.java
While debugging the infinite loop in #272, I got frustrated by the number of temporary files that I was cleaning up manually, and decided to take a detour to fix this long-standing annoyance in debugging Specimin.
I tested this change by sending SIGINT (by typing CTRL-C) to an infinite-looping Specimin process targeting the Checker Framework (i.e., my reproduction script for #272), and confirming that no temp files are left in the input directory.
=> Delete all synthetic files, even in the event of a crash, SIGINT, or SIGTERM

build.gradle, cf-loop-bug.sh, src/main/java/org/checkerframework/specimin/EnumVisitor.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/Issue272Test.java, src/test/resources/issue272/expected/com/example/PostconditionAnnotation.java, src/test/resources/issue272/expected/com/example/PreconditionAnnotation.java, src/test/resources/issue272/expected/com/example/Simple.java, src/test/resources/issue272/input/com/example/Simple.java, src/test/resources/issue272/input/com/example/StringToJavaExpression.java
Review and merge after #274 (includes the changes in that PR). Fixes the infinite loop in #272.
I was not able to find a minimal test case for this bug, unfortunately. I've confirmed that Specimin now terminates on the following input, which #272 reported caused an infinite loop and which I could repro locally:
```
--outputDirectory "/my/temp/dir" --root "/my/root/checker-framework/framework/src/main/java" --targetFile "org/checkerframework/framework/util/Contract.java" --targetMethod "org.checkerframework.framework.util.Contract#viewpointAdaptDependentTypeAnnotation(GenericAnnotatedTypeFactory<?,?,?,?>, StringToJavaExpression, Tree)"
```
=> Fix infinite loop when extending a class fails

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java
Professor,
I've made some updates so that `UnsolvedSymbolVisitor` can be more accessible for future programmers.
Initially, I attempted to write perfect specifications so that the `UnsolvedSymbolVisitor`'s functionality could be understood without the need to read the code at all. However, I found this to be more challenging than anticipated—Leslie Lamport makes it sound deceptively simple! As an alternative approach, I've added comments to clarify potentially confusing sections of the code.
Additionally, I've removed the portion of the code responsible for updating parameter types and return types of methods. That functionality is already handled within the visit method for `ClassOrInterfaceType`. (Note: The code for updating parameter types had a useful feature that checked if the …
=> Re-organizing and documenting UnsolvedSymbolVisitor

README.md
--jarPath-- is a repeatable and not required option to run Specimin.
=> Fix minor errors in README

src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/TwoTypeCorrect2Test.java, src/test/resources/twotypecorrect2/expected/com/example/Simple.java, src/test/resources/twotypecorrect2/expected/org/example/ClassOrInterfaceType.java, src/test/resources/twotypecorrect2/expected/org/example/PrimitiveType.java, src/test/resources/twotypecorrect2/expected/org/example/Type.java, src/test/resources/twotypecorrect2/input/com/example/Simple.java
The change to the infinite loop defense in `SpeciminRunner` would have prevented the infinite loop bug in #279 entirely: instead of an infinite loop, the manifestation of the bug would have been non-compilable output from Specimin, which is much less bad. I've tested that with both the new test case in this PR and the test case in #285.
=> Add an infinite loop defense and extend the fix in #285 to also handle Java 14 pattern variables

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/test/java/org/checkerframework/specimin/DifferentParamTypesTest.java, src/test/resources/differentparamtypes/expected/com/example/Simple.java, src/test/resources/differentparamtypes/input/com/example/Simple.java
When running on a method which references another method, passing in an argument which has a different type than the parameter type, the output file does not preserve the used method, resulting in unintended behavior. For example, when given this input:
```java
import java.util.ArrayList;
import java.util.List;
class Foo {
void bar() {
foo(new ArrayList<?>());
}
void foo(List<?> baz) {
}
}
```
The output only contains the `bar()` method, removing the `foo(List<?>)` method entirely:
```java
import java.util.ArrayList;
class Foo {
void bar() {
foo(new ArrayList<>());
}
}
```
This PR aims to fix this issue by checking the parameters of each method used within the target method with the imports, so they are not removed prematurely and eventually cause an `UnsolvedSymbolException`, causing the …
=> Preserve methods when argument and parameter types are different

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/PrimitiveArrayThisTest.java, src/test/resources/primitivearraythis/expected/com/example/Simple.java, src/test/resources/primitivearraythis/input/com/example/Simple.java
Fixes a set of crashes observed by @jonathan-m-phillips on Randoop of the following form:
```
Exception: java.lang.IllegalStateException,
Message: this.cumulativeSize is not NameExpr, it is FieldAccessExpr\,
Example: com.github.javaparser.ast.expr.Expression.asNameExpr(Expression.java:332)\
```
=> The scope of primitive arrays is not guaranteed to be a NameExpr

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/EnumSwitchTest.java, src/test/resources/enumswitch/expected/com/example/Analysis.java, src/test/resources/enumswitch/expected/com/example/Simple.java, src/test/resources/enumswitch/input/com/example/Analysis.java, src/test/resources/enumswitch/input/com/example/Simple.java
Based on trying to reproduce #148. The crash that that issue reports no longer is reproducible, but that input does trigger this bug.
=> Correctly preserve enum constants that are used in a switch statement, as if they were fields

build.gradle
@jonathan-m-phillips maybe this is the reason that you saw a large number of "symbol not found" errors: when I ran `./gradlew clean` followed by `./gradlew test`, I found that it fails the first time. This is surprising (and bad) behavior from Specimin's build system.
This PR fixes that sequence of commands by explicitly naming the source sets for the test target. Similar problems might exist for other targets, but I haven't found any yet. For example, running `./gradlew clean` before running the command that I mentioned in [this comment](https://github.com/njit-jerse/specimin/issues/298#issuecomment-2152430474) doesn't cause Specimin to behave any differently.
=> Avoid clean test problem

src/main/java/org/checkerframework/specimin/JavaParserUtil.java, src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/java/org/checkerframework/specimin/PrunerVisitor.java
I noticed that these methods shouldn't be in `PrunerVisitor` while reviewing the changes in #302.
=> Move some static methods from PrunerVisitor to JavaParserUtil where they belong

.github/workflows/gradle.yml, DEVELOPERS.md, build.gradle, check_differences.bat, check_differences/check_differences.bat, check_differences/test/emptydelimlines/0/emptydelimlines.txt, check_differences/test/emptydelimlines/base/emptydelimlines.txt, check_differences/test/singlefilediff/0/test.txt, check_differences/test/singlefilediff/1/test.txt, check_differences/test/singlefilediff/base/test.txt, check_differences/test/test_runner.bat, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/test/java/org/checkerframework/specimin/SpeciminTestExecutor.java, typecheck_test_outputs.bat
This PR creates the `check_differences.bat` file to substitute the lack of the `diff` command on Windows, allowing for full Windows support when running `./gradlew test`. It also ports `typecheck_test_outputs.sh` over to a `typecheck_test_outputs.bat`, which allows Windows users to call `./gradlew expectedTestOutputsMustCompile`.
=> Add Windows support for testers

src/main/java/org/checkerframework/specimin/AnnotationParameterTypesVisitor.java, src/main/java/org/checkerframework/specimin/JavaLangUtils.java, src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedAnnotationRemoverVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/test/java/org/checkerframework/specimin/InterfaceChainTest.java, src/test/resources/annoingenerictarget/expected/org/checkerframework/checker/initialization/qual/Initialized.java, src/test/resources/annoingenerictarget/expected/org/checkerframework/checker/nullness/qual/KeyForBottom.java, src/test/resources/annoingenerictarget/expected/org/checkerframework/checker/nullness/qual/NonNull.java, src/test/resources/annoingenerictarget/expected/org/checkerframework/checker/nullness/qual/Nullable.java, src/test/resources/annoingenerictarget/expected/org/checkerframework/checker/nullness/qual/UnknownKeyFor.java, src/test/resources/interfacechain/expected/com/example/Foo.java, src/test/resources/interfacechain/input/com/example/Foo.java, src/test/resources/issue272/expected/com/example/PostconditionAnnotation.java, src/test/resources/issue272/expected/com/example/PreconditionAnnotation.java, src/test/resources/syntheticannotations/expected/com/example/Anno.java, src/test/resources/syntheticannotations/expected/com/example/Bar.java, src/test/resources/syntheticannotations/expected/com/example/Baz.java, src/test/resources/syntheticannotations/expected/com/example/Foo.java, src/test/resources/syntheticannotationtarget/expected/com/example/Foo.java
This PR addresses an issue I discovered while running Specimin on [NullAway issue #102](https://github.com/uber/NullAway/issues/102), where methods in an abstract class present in the parent interface of the implemented interface were not preserved. For example:
Expected:
```java
package com.example;
import java.util.Iterator;
public class Foo<E> {
public Iterator<E> iterator() {
return new AbstractLinkedIterator() {
@Override
E computeNext() {
throw new Error();
}
};
}
public abstract class AbstractLinkedIterator implements Iterator1<E> {
abstract E computeNext();
@Override
public E next() {
throw new Error();
}
@Override
public boolean hasNext() {
throw new Error();
}
}
public interface Iterator1<E> extends Iterator<E> {
}
}
```
Actual:
```java
package com.example;
import …
```
=> Include methods for all implemented interfaces + annotation type-checker behavior preservation

src/test/java/org/checkerframework/specimin/SpeciminTestExecutor.java
Windows diff test was previously not running due to an early return statement and an error in working directory (as seen in #327 when windows passed but ubuntu didn't).
=> Fix Windows tests not running

src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/CtorTargetTest.java, src/test/resources/ctortarget/expected/com/example/Foo.java, src/test/resources/ctortarget/expected/com/example/Simple.java, src/test/resources/ctortarget/input/com/example/Foo.java, src/test/resources/ctortarget/input/com/example/Simple.java
Was broken by #325, I think. We should have had a test for this. Should fix the issue @theron-wang observed with na-323 and na-347, which both require a constructor with an argument to be targeted.
=> Fix ability to target constructors with arguments

src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/SpeciminStateVisitor.java, src/test/java/org/checkerframework/specimin/Issue103Test.java, src/test/resources/issue103/expected/com/example/AbstractLinkedDeque.java, src/test/resources/issue103/expected/com/example/AccessOrderDeque.java, src/test/resources/issue103/expected/com/example/LinkedDeque.java, src/test/resources/issue103/expected/com/example/Simple.java, src/test/resources/issue103/input/com/example/AbstractLinkedDeque.java, src/test/resources/issue103/input/com/example/AccessOrderDeque.java, src/test/resources/issue103/input/com/example/LinkedDeque.java, src/test/resources/issue103/input/com/example/Simple.java
This PR addresses an issue I found in [NullAway issue #103](https://github.com/uber/NullAway/issues/103), where compile-time errors were caused by missing methods and types. The missing methods were caused by the following:
**1) Methods not preserved**
Foo extends (abstract) Bar extends [Some JDK interface]
If Bar contains an abstract method also present in the JDK interface, those implementations in Foo were removed while the abstract definition was maintained in Bar, causing compile-time errors. A check was added to ensure that all super abstract methods did not contain anything that needed to be preserved (i.e. when in Foo, instead of just checking Bar, we check Bar and the JDK interface).
**2. Classes not preserved**
If a non-target class needs its method implementations to be …
=> Preserve `MustImplementMethodsVisitor` method type ancestors

src/main/java/org/checkerframework/specimin/PrunerVisitor.java, src/main/java/org/checkerframework/specimin/TargetMethodFinderVisitor.java, src/test/java/org/checkerframework/specimin/UnusedFuncInterfaceMethodTest.java, src/test/resources/unusedfuncinterfacemethod/expected/com/example/Bar.java, src/test/resources/unusedfuncinterfacemethod/expected/com/example/ComExampleBarUseReturnType.java, src/test/resources/unusedfuncinterfacemethod/expected/com/example/FuncInterfaceUnused.java, src/test/resources/unusedfuncinterfacemethod/expected/com/example/Simple.java, src/test/resources/unusedfuncinterfacemethod/expected/com/example/SyntheticFunction4.java, src/test/resources/unusedfuncinterfacemethod/input/com/example/FuncInterfaceUnused.java, src/test/resources/unusedfuncinterfacemethod/input/com/example/Simple.java
This PR fixes an issue present with na-791a where, even though a functional interface's method is not used, it is still being included in the output, causing compilation errors. Since the `@FunctionalInterface` annotation is removed, we should treat all interfaces equally.
=> Functional interfaces should not include a method if it's not used

DEVELOPERS.md, build.gradle, typecheck_one_test.sh, typecheck_test_outputs.sh
(on unix only, because I don't know how to write a bat script)
=> QoL improvement: typecheck just one test

src/main/java/org/checkerframework/specimin/InheritancePreserveVisitor.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/SpeciminStateVisitor.java, src/main/java/org/checkerframework/specimin/TargetMemberFinderVisitor.java, src/test/java/org/checkerframework/specimin/Issue298Test.java, src/test/java/org/checkerframework/specimin/TargetFieldTest.java
While looking into na-705, I found that Specimin ignored target fields introduced in #247, possibly when we were refactoring. The original test case `TargetField` was also not included in the original PR, so I included the test for the CI. This PR doesn't fix the issue present in na-705, however.
=> Re-add support for target fields

src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/resources/preservation_status.json
In na-97, where we target a `java/` file, the targeted file (`java/util/atomic/concurrent/Striped64.java`, I believe) was being excluded from the output because of these lines in `SpeciminRunner`:
```java
if (target.getKey().startsWith("java/")) {
continue;
}
```
The reason it worked on Windows was probably because Windows uses backslashes, and it didn't work on Unix because of the forward slash comparison here. I changed it so that the target file is preserved in the output no matter what, even if it starts with `java/` (or `java\`). This should make na-97 work on both OSes.
I didn't include a test case for this, since NullAway bugs are now in the evaluation script, but if you'd like, I could add one. Thanks!
=> include `java/` files in output if they are targeted

src/main/java/org/checkerframework/specimin/JavaParserUtil.java, src/main/java/org/checkerframework/specimin/MustImplementMethodsVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/min_program_compile_status.json, src/test/java/org/checkerframework/specimin/MethodReturnFullyQualifiedGenericTest.java, src/test/java/org/checkerframework/specimin/MethodReturnGenericTest.java, src/test/resources/methodreturnfullyqualifiedgeneric/expected/com/bar/Bar.java, src/test/resources/methodreturnfullyqualifiedgeneric/expected/com/example/Simple.java, src/test/resources/methodreturnfullyqualifiedgeneric/expected/com/foo/InOtherPackage2.java, src/test/resources/methodreturnfullyqualifiedgeneric/input/com/example/Simple.java, src/test/resources/methodreturngeneric/expected/com/bar/Bar.java, src/test/resources/methodreturngeneric/expected/com/example/InSamePackage.java, src/test/resources/methodreturngeneric/expected/com/example/Simple.java, src/test/resources/methodreturngeneric/expected/com/foo/InOtherPackage.java, src/test/resources/methodreturngeneric/expected/com/foo/InOtherPackage2.java, src/test/resources/methodreturngeneric/input/com/example/Simple.java, typecheck_one_test.sh, typecheck_test_outputs.bat
Previously, when a synthetic method with a generic return type had a type parameter in the same package as the target method, it would not keep its fully qualified name in its synthetic definition, leading to compilation errors seen in na-791b.
For example, `ImmutableSet.copyOf` returned an `ImmutableSet<Feature>`, but in its synthetic definition, `copyOf` returned `com.google.common.collect.ImmutableSet<Feature>` instead of `com.google.common.collect.ImmutableSet<com.github.benmanes.caffeine.cache.Feature>`.
=> Fully qualify types in generic synthetic method return types

src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/resources/preservation_status.json, src/test/resources/nullaway-ctors/expected/com/example/Simple.java, src/test/resources/nullaway-ctors/input/com/example/Simple.java
This fixes NA-347 (with the modularity model changes in specimin-evaluation#9)
=> Call the correct generic "solve a type" method in UnsolvedSymbolVisitor when using the NA modularity model

check_differences/check_differences.bat, check_differences/test/test_runner.bat, src/test/java/org/checkerframework/specimin/SpeciminTestExecutor.java, src/test/resources/abstractimpl/expected/com/example/Simple.java, typecheck_one_test.bat, typecheck_test_outputs.bat
This ports over the changes made in #335 to Windows, and it should also finally fix false positives regarding `check_differences.bat`.
=> Port `typecheck_one_test.sh` to batch and fix `check_differences.bat`

src/main/java/org/checkerframework/specimin/AnnotationParameterTypesVisitor.java, src/main/java/org/checkerframework/specimin/JavaParserUtil.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMemberFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedAnnotationRemoverVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedClassOrInterface.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/main/java/org/checkerframework/specimin/UnusedImportRemoverVisitor.java, src/test/java/org/checkerframework/specimin/JavaParserUtilIsAClassPathTest.java, src/test/java/org/checkerframework/specimin/UnusedImportsTest.java, src/test/resources/abstractimpl/expected/com/example/Simple.java, src/test/resources/issue103/expected/com/example/AccessOrderDeque.java, src/test/resources/preserveannotations/expected/com/example/Foo.java, src/test/resources/unsolvedmethodtypecorrect/expected/com/example/Simple.java, src/test/resources/unsolvedstaticmethod/expected/com/example/Simple.java, src/test/resources/unusedimports/expected/com/example/ManyImports.java, src/test/resources/unusedimports/expected/com/example/Simple.java, src/test/resources/unusedimports/input/com/example/ManyImports.java, src/test/resources/unusedimports/input/com/example/Simple.java, src/test/resources/voidreturndouble/expected/com/example/MyFoo.java, src/test/resources/whenthen/expected/com/example/Simple.java
Removes unused imports in all output files.
Take, for example, `ManyImports` in the included test case.
Previously:
```java
package com.example;
import java.util.List;
import java.io.*;
import static java.util.Map.*;
import static java.lang.Math.sqrt;
import static java.lang.Math.PI;
public class ManyImports {
}
```
Now:
```java
package com.example;
public class ManyImports {
}
```
Even if the import type is a used type element, it should still be removed if the current, minimized file does not contain any instances.
=> Remove unused imports

src/main/java/org/checkerframework/specimin/JavaParserUtil.java, src/main/java/org/checkerframework/specimin/SpeciminRunner.java, src/main/java/org/checkerframework/specimin/TargetMemberFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/BuiltinEnumTest.java, src/test/java/org/checkerframework/specimin/DefaultPackageTest.java, src/test/java/org/checkerframework/specimin/Issue368Test.java, src/test/resources/defaultpackage/expected/A.java, src/test/resources/defaultpackage/input/A.java, src/test/resources/enumbuiltin/expected/com/example/Scheduler.java, src/test/resources/enumbuiltin/input/com/example/Scheduler.java, src/test/resources/issue368/A_code.java, src/test/resources/issue368/expected/com/example/A.java, src/test/resources/issue368/expected/com/example/B.java, src/test/resources/issue368/input/com/example/A.java, src/test/resources/issue368/input/com/example/B.java
Fix issue #368 , issue #370 , and issue #361 .
Tests have been added.
One existing test(Issue103) fails, but it was already failing in the main branch.
=> Fix issues #368, #370, #361

CI_repository_list.csv
This changes the url that gets pulled to run the CI script to a fork on my account that won't change.
=> changed repository link to point towards a static fork

.github/workflows/check_compilable_percentage.yml, ashe_scripts/de-interleave-ashe-log.py, ashe_scripts/run_ashe_for_stats.py
When I multithreaded ASHE to speed up CI checks, I made the logs print out in a random order. This should filter it by thread and then sort the results alphabetically so it remains consistent regardless of how many threads the CI tests run on.
This should also let me figure out what failed during CI for #381.
If this PR passes CI don't merge it yet, I need to diff the results from this with my own results before that happens.
=> Deinterlace multithreaded logs

src/main/java/org/checkerframework/specimin/TargetMemberFinderVisitor.java, src/main/java/org/checkerframework/specimin/UnsolvedSymbolVisitor.java, src/test/java/org/checkerframework/specimin/ArrayTypeParamTest.java, src/test/resources/arraytypeparam/expected/com/example/Simple.java, src/test/resources/arraytypeparam/input/com/example/Simple.java
This caused some crashes in PlumeUtil's `Intern.java`, so I'll need to update the % of passing methods.
=> Fix crash when a type parameter in a field declaration has an array type
